import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='min-h-svh'>
        <header className="w-full h-40 flex justify-center ">
          <div className="max-w-7xl w-full flex items-center justify-between sm:px-16 px-6">
            <Link href="/blog">
              <Image
                src="/img/logo/logo-spark.png"
                alt="Logo"
                width={32}
                height={32}
              />
            </Link>
            <div className="flex items-center gap-4">
              <Link
                href="/blog/article/new"
                className="text-white bg-zinc-950 hover:bg-zinc-800 rounded-full px-4 py-2 transition duration-200"
              >
                Créer un article
              </Link>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="w-8 h-8" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5"/>
              </svg>
            </div>
          </div>
        </header>
        <main className="relative z-10 flex justify-center min-h-[calc(100svh-160px)] items-center flex-col max-w-7xl mx-auto sm:px-16 px-6 pb-16">
          {children}
        </main>
        <footer className="bg-zinc-950 text-white ">
          <div>
            <div className="max-w-7xl h-80 mx-auto py-8 px-16 flex flex-wrap justify-between items-center">
              <div>
                <Image
                  src="/img/logo/logo-spark.png"
                  alt="Logo"
                  width={64}
                  height={64}
                  className="mix-blend-difference"
                />
              </div>
              <div className="flex flex-col gap-4 text-lg">
                <div className="flex gap-8">
                  <Link href="/blog" className="hover:opacity-60 transition duration-200">
                    Blog
                  </Link>
                  <Link href="/" className="hover:opacity-60 transition duration-200">
                    Créer un article
                  </Link>
                </div>
                <div className="flex justify-between gap-8 ">
                  <Link href="/" className="hover:opacity-60 transition duration-200">
                    À propos
                  </Link>
                  <Link href="/" className="hover:opacity-60 transition duration-200">
                    Contact
                  </Link>
                </div>
              </div>
            </div>
          </div>
          <div className="max-w-7xl mx-auto py-8">
            <p className="text-center text-sm text-zinc-500">
              &copy; 2021 Spark. All rights reserved.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
